encoding: utf-8

# SEO相关信息
title: HRVIUN
description: HRVIUN

author: Srijeahqo
footerText: Hrviun

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://h.hrviun.eu.org'
baseurl: ''


# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 功能
    url: /pages/links.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: true
#math
extMathjax: true

# 显示访问量统计，由不蒜子提供服务
extCount: true
#评论
comments:
  gitalk: true
  gitalk_clientID: '11d451753b22bbf19b77'
  gitalk_Secret: 'ccffc2a474552be7e18ae21b813106f5b499611c'
  gitalk_repo: '用户名.github.io'
  gitalk_owner: '用户名'
  gitalk_admin: '用户名'
  distractionFreeMode: true
# 功能
links:
  # - title: 名
  #   url: 链接
  